console.log(typeof null);
console.log(0.1 + 0.2 === 0.3);
console.log([] + {});
console.log(1 + '2' + '3');
console.log('5' - 3);
console.log(typeof NaN);
console.log([1, 2] == [1, 2]);
console.log(!!null);
console.log(2 + '2' - 1);
console.log(false == '0');
console.log(typeof ({}));
// console.log([1, 2, 3] === [1, 2, 3]);
console.log(0 == '');
console.log(null == undefined);
console.log('a' + + 'b');
console.log([1, 2] + [3, 4]);
console.log(1 == '1');
console.log(typeof [] === 'object');
console.log('5' + 5);
console.log(1 < 2 < 3);
console.log(!!(1 && 0));
console.log('0' == false);
console.log([1, 2, 3].map(n => n * n));
console.log(3 == 3 == 3);
console.log(1 + 2 + '3' + 4 + 5);
console.log(typeof (function() {}));
console.log([2] == [2]);
console.log('' + 1 + 0);
console.log(2 && 3 && null);
console.log([null] == [undefined]);
